spring:
  server:
    port: 8082
  application:
    name: transaction-sink-application
  integration:
    poller:
      fixed-delay: 5000
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker:9092
      bindings:
        sinkToConsole-in-0:
          destination: enriched-transactions
        cashCardTransactionFileSink-in-0:
          destination: enriched-transactions
    function:
      definition: sinkToConsole;cashCardTransactionFileSink