### Publish a new CashCard Transaction
POST http://localhost:8080/pub
Content-Type: application/json

{
  "id": 1234,
  "cashCard": {
    "id": 12345,
    "owner": "testOwner",
    "amountRequestedForAuth": 3.14
  }
}