springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
info:
  api:
    title: CashCard Transaction Source API
    description: API for publishing cash card transactions to a Kafka topic.
    version: 0.0.1

spring:
  server:
    port: 8080
  application:
    name: transaction-source-application
  integration:
    poller:
      fixed-delay: 5000
  cloud:
    stream:
      bindings:
        approvalRequest-out-0:
          destination: approval-requests
          producer:
            configuration:
              value:
                serializer: com.example.demo.serdes.TransactionSerializer
      kafka:
        binder:
          brokers: broker:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env