spring:
  server:
    port: 8080
  application:
    name: transaction-source-application
  integration:
    poller:
      fixed-delay: 5000
  cloud:
    stream:
      bindings:
        approvalRequest-out-0:
          destination: approval-requests
          producer:
            configuration:
              value:
                serializer: com.example.demo.serdes.TransactionSerializer
      kafka:
        binder:
          brokers: broker:9092

