spring:
  boot:
    admin:
      client:
        url: http://admin-server:9090
  server:
    port: 8084
  application:
    name: transaction-enricher-application
  integration:
    poller:
      fixed-delay: 5000
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker:9092
      bindings:
        enrichTransaction-in-0:
          destination: approval-requests
          group: enrich-consumer
          consumer:
            batch-mode: true
            auto-offset-reset: earliest
            configuration:
              key:
                deserializer: org.apache.kafka.common.serialization.StringDeserializer
              value:
                deserializer: com.example.demo.serdes.TransactionDeserializer
        enrichTransaction-out-0:
          destination: enriched-transactions
          producer:
            configuration:
              key:
                serializer: org.apache.kafka.common.serialization.StringSerializer
              value:
                serializer: com.example.demo.serdes.EnrichedTransactionSerializer
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always